image:
  file: Dockerfile.dev

tasks:
  - init: gem install bundler:2.2.9 && bundle install
    command: bundle exec jekyll serve --live-reload
    openMode: split-right

ports:
  - port: 4000
    onOpen: open-browser
