image:
  file: .gitpod.Dockerfile

tasks:
  - init: gem install bundler:2.2.9 && bundle install
    command: bundle exec jekyll serve --livereload
    openMode: split-right

ports:
  - port: 4000
    onOpen: open-browser
