# Site settings
title: Pioneers in Engineering
email: leadership@pioneers.berkeley.edu
description: >
  © Pioneers in Engineering Foundation 2015. </br>
  Licensed under CC-BY-4.0.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pioneers.berkeley.edu" # the base hostname & protocol for your site
twitter_username: PieRobotics
github_username:  pioneers
facebook_username: pierobotics
youtube_username: pierobotics
instagram_username: pierobotics
host: 0.0.0.0

# Build settings
markdown: kramdown
